config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'pages/home'
  get 'pages/about'
  resources :users

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_tenant

  has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }

  # def full_name
  #   self.first_name + " " + self.last_name
  # end
  
  private

  def create_tenant
    Apartment::Tenant.create(subdomain)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

  def sign_up_params
    params.require(:user).permit(:first_name, 
                                 :last_name, 
                                 :email, 
                                 :password, 
                                 :password_confirmation, 
                                 :username,
                                 :subdomain)
  end

  def account_update_params
    params.require(:user).permit(:first_name, 
                                 :last_name, 
                                 :email, 
                                 :password, 
                                 :password_confirmation, 
                                 :current_password, 
                                 :username,
                                 :subdomain)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :show]
  def index
    @users = User.all
  end

  def show
  end                                                                    

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HockeySchool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary rounded">
  <a class="navbar-brand" href="#">Navbar</a>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link">Left Link 1</a>
    </li>
    <li class="nav-item">
      <a class="nav-link">Left Link 2</a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link">Right Link 1</a>
    </li>
   <% if user_signed_in? %> 
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.name.first %></a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </li>
<% else # user not signed it %>
    <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %> </li>
    <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %> </li>
<% end %>
  </ul>
</nav>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
      <% @users.each do |user| %>
          <div class="col-md-4 d-flex">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="..." alt="Card image cap">
                <div class="card-body flex-fill">
                  <h5 class="card-title"><%= user.name %></h5>
                  <h3>subdomain</h3>
                  <p class="card-text"><%= user.subdomain %></p>
                  <%= link_to 'User Profile', user_path(user), class: "btn btn-primary" %>
                </div>
            </div>
          </div>
      <% end %> 
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
          <div class="col-md-12 d-flex">
            <div class="card" style="width: 100%;">
                <img class="card-img-top" src="..." alt="Card image cap">
                <div class="card-body flex-fill">
                  <h5 class="card-title"><%= @user.name %></h5>
                  <p class="card-text"><%= @user.subdomain %></p>
                  <a href="#" class="btn btn-primary">Visit Domain</a>
                </div>
            </div>
          </div>

  </div>
</div>